export type AltanaBoundaryErrorCode =
  | "INVALID_ADDRESS"
  | "INVALID_SELECTOR"
  | "INVALID_CHAIN"
  | "INVALID_EXPIRY"
  | "EMPTY_ALLOWLIST"
  | "INVALID_SPEND_LIMIT"
  | "POLICY_BOUND_EXCEEDED"
  | "CALL_NOT_ALLOWED"
  | "NATIVE_VALUE_EXCEEDED"
  | "SESSION_MATERIAL_EMPTY"
  | "SESSION_MATERIAL_CONSUMED"
  | "SESSION_HANDOFF_FAILED"
  | "SESSION_NOT_ACTIVE"
  | "SENSITIVE_EVIDENCE_FIELD"
  | "INVALID_EVIDENCE_VALUE";

/**
 * Error type intended for structured application envelopes.  `message` is
 * deliberately short and generated by this package; adapter errors must be
 * mapped to one of these codes before they are placed in evidence or logs.
 */
export class AltanaBoundaryError extends Error {
  readonly code: AltanaBoundaryErrorCode;
  readonly retriable: boolean;

  constructor(
    code: AltanaBoundaryErrorCode,
    message: string,
    options: { retriable?: boolean } = {},
  ) {
    super(message);
    this.name = "AltanaBoundaryError";
    this.code = code;
    this.retriable = options.retriable ?? false;
  }
}

export function safeErrorCode(error: unknown): string {
  if (error instanceof AltanaBoundaryError) return error.code;

  if (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    typeof error.code === "string" &&
    /^[A-Z][A-Z0-9_]{1,63}$/.test(error.code)
  ) {
    return error.code;
  }

  return "EXTERNAL_ADAPTER_ERROR";
}

