import { AppError } from "@bnbera/config";

export type IngestionErrorCode =
  | "INGESTION_INPUT_INVALID"
  | "INGESTION_SOURCE_UNSUPPORTED"
  | "IDENTITY_CONFLICT"
  | "DUPLICATE_CHAIN_LOG_CONFLICT"
  | "CHECKPOINT_CONFLICT"
  | "REORG_RECONCILIATION_REQUIRED"
  | "CLAIM_OWNER_MISMATCH"
  | "CLAIM_PROOF_INVALID"
  | "CLAIM_NOT_ACTIVE"
  | "CLAIM_CONFLICT"
  | "CLAIM_AUTHORIZATION_REQUIRED"
  | "SERVICE_INVALID"
  | "SERVICE_PROBE_FAILED"
  | "SERVICE_URL_INVALID"
  | "SERVICE_HTTPS_REQUIRED"
  | "SERVICE_SSRF_BLOCKED"
  | "SERVICE_DNS_REBINDING"
  | "SERVICE_DNS_LOOKUP_FAILED"
  | "SERVICE_REDIRECT_BLOCKED"
  | "SERVICE_RESPONSE_TOO_LARGE"
  | "SERVICE_MIME_UNSUPPORTED"
  | "SERVICE_PROBE_TIMEOUT"
  | "SERVICE_PROBE_CANCELLED"
  | "SERVICE_AUTH_REQUIRED"
  | "SERVICE_RATE_LIMITED"
  | "SERVICE_ENDPOINT_NOT_FOUND"
  | "SERVICE_STATUS_NOT_HEALTHY"
  | "SERVICE_UPSTREAM_UNAVAILABLE"
  | "SERVICE_A2A_AGENT_CARD_INVALID"
  | "SERVICE_MCP_CONTRACT_INVALID"
  | "SERVICE_READINESS_INVALID"
  | "SERVICE_READINESS_NOT_READY"
  | "SERVICE_X402_CHALLENGE_INVALID"
  | "SERVICE_X402_CHALLENGE_REQUIRED"
  | "SERVICE_ADAPTER_CONTRACT_INVALID"
  | "SERVICE_PROTOCOL_UNSUPPORTED"
  | "CHAIN_PROVIDER_INVALID"
  | "CHAIN_PROVIDER_UNAVAILABLE"
  | "CHAIN_PROVIDER_ERROR"
  | "CHAIN_NETWORK_MISMATCH"
  | "SCAN_CONFIG_INVALID"
  | "SCAN_CONTRACT_INVALID"
  | "SCAN_AUTH_FAILED"
  | "SCAN_RATE_LIMITED"
  | "SCAN_UNAVAILABLE"
  | "SCAN_TIMEOUT"
  | "SCAN_CIRCUIT_OPEN"
  | "SCAN_JOB_CONFIG_INVALID"
  | "SCAN_JOB_CANCELLED"
  | "SCAN_JOB_ALREADY_RUNNING"
  | "SCAN_JOB_CHECKPOINT_CONFLICT"
  | "SCAN_JOB_PROVIDER_INVALID"
  | "METADATA_URI_INVALID"
  | "METADATA_FETCH_FAILED"
  | "METADATA_TOO_LARGE"
  | "METADATA_MIME_UNSUPPORTED"
  | "METADATA_SSRF_BLOCKED"
  | "METADATA_PARSE_FAILED"
  | "CATEGORY_CLASSIFICATION_FAILED"
  | "EMBEDDING_CONFIG_INVALID"
  | "EMBEDDING_AUTH_FAILED"
  | "EMBEDDING_RATE_LIMITED"
  | "EMBEDDING_TIMEOUT"
  | "EMBEDDING_RESPONSE_INVALID"
  | "EMBEDDING_PROVIDER_FAILED"
  | "EMBEDDING_DIMENSION_MISMATCH"
  | "EMBEDDING_VERSION_CONFLICT"
  | "EMBEDDING_BACKFILL_CONFIG_INVALID"
  | "EMBEDDING_BACKFILL_CHECKPOINT_CONFLICT"
  | "EMBEDDING_BACKFILL_CANCELLED"
  | "EMBEDDING_BACKFILL_ALREADY_RUNNING"
  | "EMBEDDING_BACKFILL_SOURCE_INVALID"
  | "REPOSITORY_FAILURE";

export function ingestionError(
  code: IngestionErrorCode,
  safeMessage: string,
  nextAction: string,
  cause?: unknown,
  retriable = false
): AppError {
  return new AppError({
    code,
    safeMessage,
    requestId: "agent-ingestion",
    nextAction,
    retriable,
    cause
  });
}
