import Link from "next/link";
import type { MarketplaceAgentReadModel } from "@/lib/marketplace-contract";
import { AgentAvatar } from "./agent-avatar";
import { AgentReviews } from "./agent-decision-summary";
import { DirectoryActions } from "./directory-actions";
import { categoryLabel, formatObservedAt } from "@/lib/presentation";

function formatRelativeObservation(value: string | null, now = Date.now()): string {
  if (!value) return "Not reported";
  const elapsed=Math.max(0,now-Date.parse(value));
  if(!Number.isFinite(elapsed))return "Not reported";
  if(elapsed<60000)return "Just now";
  if(elapsed<3600000)return `${Math.floor(elapsed/60000)}m ago`;
  if(elapsed<86400000)return `${Math.floor(elapsed/3600000)}h ago`;
  return `${Math.floor(elapsed/86400000)}d ago`;
}
export const relativeObservation = formatRelativeObservation;
export function DirectoryScore({score,large=false}:{readonly score:number|null;readonly large?:boolean}) {
  return <div className={`directory-score${large?" directory-score--large":""}`} title="8004scan overall score, out of 100. A vendor ranking signal, not a verified-purchase rating."><svg viewBox="0 0 64 64" aria-hidden="true"><circle className="directory-score__track" cx="32" cy="32" r="28"/><circle className="directory-score__value" cx="32" cy="32" r="28" pathLength="100" strokeDasharray={`${score??0} 100`}/></svg><strong>{score===null?"—":score.toFixed(1)}</strong><span className="sr-only">8004scan score out of 100</span></div>;
}
export function DirectoryAgentRow({agent}:{readonly agent:MarketplaceAgentReadModel}) {
  const data=agent.directory!;
  const relativeObservation = (value:string|null) => formatRelativeObservation(value,Date.parse(data.renderedAt??data.fetchedAt));
  const checked=data.cardCheck.status==="reachable";
  return <article className="agent-row directory-row">
    <Link className="agent-row__art" href={`/agents/${agent.slug}`} aria-label={`View ${agent.name}`}><AgentAvatar category={agent.category} imageUrl={data.imageUrl} name={agent.name}/></Link>
    <div className="agent-row__content"><div className="directory-row__title"><h3><Link href={`/agents/${agent.slug}`}>{agent.name}</Link></h3><span className={`chain-chip${agent.identity.chainId===97?" chain-chip--testnet":""}`}><span aria-hidden="true">◆</span> {agent.identity.chainId===56?"BNB Chain":"Testnet"}</span></div><p className="agent-row__description">{agent.description}</p><div className="directory-row__signals"><span title="Feedback indexed by 8004scan; permissionless, not verified BNBEra purchases">☆ {data.feedback.count?.toLocaleString()??"—"} feedback{data.feedback.average!==null?` · ${data.feedback.average.toFixed(1)}/100`:""}</span><span title={`8004scan profile update: ${formatObservedAt(data.vendorUpdatedAt)}`}>◷ Updated {relativeObservation(data.vendorUpdatedAt)}</span>{data.cardCheck.observedAt&&<span className={checked?"signal-positive":""} title="A read-only Agent Card check. It does not prove task execution."><i/>Card {checked?"checked":"unreachable"} · {relativeObservation(data.cardCheck.observedAt)}</span>}</div><div className="directory-row__protocols">{data.protocols.slice(0,4).map(protocol=><span key={protocol}>{protocol}</span>)}{agent.category!=="uncategorized"&&<span>{categoryLabel(agent.category)}</span>}</div></div>
    <div className="directory-row__score"><DirectoryScore score={data.scores.overall}/><span>8004scan score</span></div>
    <div className="agent-row__actions"><Link className="button button--primary" href={`/agents/${agent.slug}`}>Explore agent <span aria-hidden="true">↗</span></Link><small>Registered on-chain</small></div>
  </article>;
}

export function DirectoryAgentProfile({agent}:{readonly agent:MarketplaceAgentReadModel}) {
  const data=agent.directory!;
  const relativeObservation = (value:string|null) => formatRelativeObservation(value,Date.parse(data.renderedAt??data.fetchedAt));
  const explorer=agent.identity.chainId===56?"https://bscscan.com":"https://testnet.bscscan.com";
  const dimensions=[{name:"Quality",value:data.scores.quality},{name:"Activity",value:data.scores.activity},{name:"Metadata",value:data.scores.metadata},{name:"Health",value:data.scores.health}];
  return <div className="page-shell directory-profile">
    <div className="directory-breadcrumb"><Link href="/marketplace">← All agents</Link><span>/</span><span>{agent.name}</span></div>
    <section className="directory-profile__hero"><div className="directory-profile__identity"><AgentAvatar category={agent.category} imageUrl={data.imageUrl} name={agent.name}/><div><div className="directory-profile__labels"><span className="chain-chip">◆ {agent.identity.chainId===56?"BNB Chain · Mainnet":"BNB Chain · Testnet"}</span><span>ERC-8004 #{agent.identity.agentId}</span></div><h1>{agent.name}</h1><div className="directory-profile__subline"><span className="signal-positive">✓ Registry confirmed</span><span>Updated {relativeObservation(data.vendorUpdatedAt)}</span><span>{data.feedback.count??"—"} public feedback</span></div></div></div><DirectoryActions slug={agent.slug} name={agent.name}/></section>
    <div className="directory-profile__layout"><div className="directory-profile__main"><section className="directory-overview"><span className="eyebrow">Meet your next agent</span><p>{agent.description}</p><div className="directory-service-tags">{data.protocols.map(protocol=><span key={protocol}>{protocol}</span>)}{agent.category!=="uncategorized"&&<span>{categoryLabel(agent.category)}</span>}</div></section>
      <nav className="profile-nav" aria-label="Agent sections"><a href="#services">Services <span>{data.services.length}</span></a><a href="#reputation">Reputation</a><a href="#reviews">Reviews</a><a href="#onchain">On-chain</a><a href="#technical-details">Metadata</a></nav>
      <section className="directory-section" id="services"><div className="profile-section-heading"><h2>Services & capabilities</h2><span>{data.services.length} advertised</span></div>{data.skills.length>0&&<div className="directory-skills">{data.skills.map(skill=><article key={skill.id}><span aria-hidden="true">↗</span><div><h3>{skill.name}</h3><p>{skill.description}</p></div></article>)}</div>}<div className="directory-services">{data.services.length?data.services.map((service,index)=><article key={`${service.url}-${index}`}><div className="directory-service-icon" aria-hidden="true">{service.name.toLowerCase()==="a2a"?"⌘":service.name.toLowerCase()==="mcp"?"◇":"↗"}</div><div><h3>{service.name}</h3><p>{new URL(service.url).hostname}{service.version?` · v${service.version}`:""}</p></div><a className="button" href={service.url} target="_blank" rel="noreferrer">Open service ↗</a></article>):<p className="directory-empty">No public service endpoint was supplied in this registration.</p>}</div><p className="directory-footnote">Published by the agent. Opening a service does not authorize a transaction or verify a result.</p></section>
      <section className="directory-section" id="reputation"><div className="profile-section-heading"><h2>Reputation & quality</h2><a href={data.sourceUrl} target="_blank" rel="noreferrer">Source: 8004scan ↗</a></div><div className="directory-quality"><div><DirectoryScore score={data.scores.overall} large/><h3>Overall score</h3><p>8004scan · out of 100</p></div><div className="directory-dimensions">{dimensions.map(dimension=><div key={dimension.name}><div><span>{dimension.name}</span><strong>{dimension.value===null?"Not measured":dimension.value.toFixed(1)}</strong></div><div className="directory-meter"><span style={{width:`${dimension.value??0}%`}}/></div></div>)}</div></div><p className="directory-footnote">{data.scores.algorithm??"Vendor ranking"} · Scored {relativeObservation(data.scores.observedAt)}. These vendor signals are separate from buyer reviews and BNBEra hire eligibility.</p><div className="directory-stat-grid"><article><strong>{data.feedback.count?.toLocaleString()??"—"}</strong><span>Public feedback</span><small>Indexed by 8004scan</small></article><article><strong>{data.feedback.average===null?"—":data.feedback.average.toFixed(1)}</strong><span>Feedback average /100</span><small>Permissionless feedback</small></article><article><strong>{data.stats.validations?.toLocaleString()??"—"}</strong><span>Validation records</span><small>Indexed by 8004scan</small></article></div></section>
      <section className="directory-section"><div className="profile-section-heading"><h2>Community feedback</h2><a href={`${data.sourceUrl}#feedback`} target="_blank" rel="noreferrer">View on 8004scan ↗</a></div>{data.feedback.items.length?<div className="directory-feedback">{data.feedback.items.map((item,index)=><article key={index}><div><strong>{item.reviewer?`${item.reviewer.slice(0,8)}…${item.reviewer.slice(-4)}`:"Public reviewer"}</strong><span>{item.value??"—"}{item.tag?` · ${item.tag}`:""}</span></div><p>{item.comment??"This reviewer left a score without a public comment."}</p><small>{formatObservedAt(item.observedAt)} · 8004scan indexed feedback</small></article>)}</div>:<p className="directory-empty">{data.feedback.count===0?"No public feedback yet. This is an early opportunity to explore the agent's services.":"Review records are available through the source link."}</p>}</section>
      <AgentReviews agent={agent}/>
      <DirectoryPublicArtifacts agent={agent}/>
      <section className="directory-section" id="onchain"><div className="profile-section-heading"><h2>On-chain identity</h2><span className="signal-positive">✓ Finalized block {agent.dataProvenance.identityRead.observedBlock?.toLocaleString()}</span></div><div className="directory-chain-links"><a href={`${explorer}/token/${agent.identity.identityRegistry}?a=${agent.identity.agentId}`} target="_blank" rel="noreferrer"><span>ERC-8004 registration</span><strong>Agent #{agent.identity.agentId} ↗</strong></a>{agent.ownerAddress&&<a href={`${explorer}/address/${agent.ownerAddress}`} target="_blank" rel="noreferrer"><span>Owner wallet</span><strong>{agent.ownerAddress.slice(0,8)}…{agent.ownerAddress.slice(-6)} ↗</strong></a>}{data.createdTransaction&&<a href={`${explorer}/tx/${data.createdTransaction}`} target="_blank" rel="noreferrer"><span>Registration transaction</span><strong>View transaction ↗</strong></a>}<a href={data.sourceUrl} target="_blank" rel="noreferrer"><span>Agent explorer</span><strong>View on 8004scan ↗</strong></a></div></section>
      <details className="profile-technical" id="technical-details"><summary>Technical details <span>Registry, metadata & source evidence</span></summary><dl className="directory-metadata"><dt>Full identity</dt><dd><code>{agent.id}</code></dd><dt>Identity registry</dt><dd><a href={`${explorer}/address/${agent.identity.identityRegistry}`} target="_blank" rel="noreferrer">{agent.identity.identityRegistry} ↗</a></dd><dt>Owner</dt><dd><code>{agent.ownerAddress??"Unavailable"}</code></dd><dt>Agent wallet</dt><dd><code>{agent.agentWallet??"Not registered"}</code></dd><dt>Metadata resolution</dt><dd>{data.registration.status}{data.registration.reason?` · ${data.registration.reason}`:""}</dd><dt>Registration URI</dt><dd><code>{data.registration.uri??"Unavailable"}</code></dd><dt>Content SHA-256</dt><dd><code>{data.registration.digest??"Unavailable"}</code></dd><dt>Observed block</dt><dd>{agent.dataProvenance.identityRead.observedBlock} · finalized</dd><dt>Block hash</dt><dd><code>{agent.dataProvenance.identityRead.observedBlockHash}</code></dd><dt>Profile refreshed</dt><dd>{formatObservedAt(data.fetchedAt)}</dd><dt>Separate state axes</dt><dd>{Object.entries(agent.stateAxes).map(([key,value])=><span key={key}>{key}: {value}<br/></span>)}</dd></dl></details>
    </div><aside className="directory-profile__aside"><section className="directory-availability"><div className="directory-aside-icon" aria-hidden="true">⌁</div><h2>Agent availability</h2><div className="directory-status-line"><i data-state={data.cardCheck.status}/><strong>{data.cardCheck.status==="reachable"?"Agent Card reachable":data.cardCheck.status==="unreachable"?"Card check failed":"Awaiting service check"}</strong></div><p>{data.cardCheck.observedAt?`Checked ${relativeObservation(data.cardCheck.observedAt)}${data.cardCheck.latencyMs===null?"":` · ${data.cardCheck.latencyMs.toLocaleString()} ms`}`:"No Agent Card has been probed yet."}</p><div className="directory-aside-divider"/><div className="directory-aside-kv"><span>BNBEra hires</span><strong>{agent.metrics.completedJobs.completedCount??"—"}</strong></div><div className="directory-aside-kv"><span>Verified buyer reviews</span><strong>{agent.metrics.reputation.verifiedPurchases.count??"—"}</strong></div><div className="directory-aside-kv"><span>Registered</span><strong>{relativeObservation(data.createdAt)}</strong></div><button className="button button--primary" disabled>Hire unavailable</button><small>A supported quote and callable service must be verified before hiring through BNBEra.</small></section><section className="directory-monitor-note"><span aria-hidden="true">◷</span><div><strong>Every signal has a source</strong><p>A card check confirms reachability. Uptime and successful tasks require monitoring and result history.</p></div></section><a className="directory-source-link" href={data.sourceUrl} target="_blank" rel="noreferrer">Explore the full source profile ↗</a></aside></div>
  </div>;
}

function DirectoryPublicArtifacts({agent}:{readonly agent:MarketplaceAgentReadModel}) {
  const artifacts=[agent.evidence.profile,agent.evidence.runBundle].filter(artifact=>artifact.status!=="unavailable");
  if(!artifacts.length)return null;
  return <section className="directory-section"><div className="profile-section-heading"><h2>Published evidence</h2><span>Greenfield · independently recorded</span></div><div className="directory-feedback">{artifacts.map(artifact=><article key={artifact.artifactType}><div><strong>{artifact.artifactType==="agent_profile"?"Agent profile snapshot":"Completed-job result"}</strong><span>{artifact.status}</span></div><p>Version {artifact.version??"unavailable"}{artifact.version!==agent.evidence.currentVersion?" · Historical snapshot":""}{artifact.jobId?` · Job ${artifact.jobId}`:""}</p>{artifact.status==="verified"&&artifact.readUrl&&<a className="text-link" href={artifact.readUrl} target="_blank" rel="noreferrer">Open verified JSON ↗</a>}<small>Verified {formatObservedAt(artifact.verifiedAt)}</small><details><summary>Integrity details</summary><p>{artifact.summary}</p><p>SHA-256: <code>{artifact.sha256Digest??"Unavailable"}</code></p><p>Keccak: <code>{artifact.keccak256Digest??"Unavailable"}</code></p><p>{artifact.status==="verified"&&!artifact.sealTransactionHash?"Seal confirmed; transaction hash unavailable.":artifact.sealTransactionHash??"Seal not confirmed"}</p></details></article>)}</div></section>;
}
